service: boilerplate-nextjs-nestjs-vite-tailwind

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  api:
    handler: server-handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 4000

  serverless-offline:
    httpPort: 3001
    lambdaPort: 3003
    websocketPort: 3004
    noPrependStageInUrl: true
    corsConfig:
      origin: '*'
      allowCredentials: false